-- APAGANDO A BASE DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXEMPLO02;

-- CONECTANDO A BASE DE DADOS
USE DBEXEMPLO02;

-- CRIANDO AS TABELAS 
CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL
    ,NOME VARCHAR (120) NOT NULL
    ,IDNASCIMENTO DATE
    ,TELEFONE_CELULAR VARCHAR(15)
    ,TELEFONE_RESIDENCIAL VARCHAR(15)
    ,TELEFONE_COMERCIAL VARCHAR(15)
    ,RUA VARCHAR(100)
    ,NUMERO INT 
    ,COMPLEMENTO VARCHAR(100)
    ,BAIRRO VARCHAR(100)
    ,CIDADE VARCHAR(100)
    ,ESTADO CHAR(2)
    ,CEP CHAR(8)
    ,PRIMARY KEY (IDCLIENTE)
);