DROP DATABASE IF EXISTS EXERCICIO06;

CREATE DATABASE EXERCICIO06;

USE  EXERCICIO06;

CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(160)
    , IDADE INT 
    , RUA VARCHAR(160)
    , NUMERO INT
    , BAIRRO VARCHAR (160)
    , CIDADE VARCHAR (160)
    , ESTADO CHAR(2)
    , CEP CHAR (8)
    , COMPLEMENTO VARCHAR(160)
    , PRIMARY KEY (IDALUNO)
);