DROP DATABASE IF EXISTS DBEXERCICIO05;

CREATE DATABASE DBEXERCICIO05;

USE DBEXERCICIO05;

CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(160) 
    , DATA_DE_NASCIMENTO DATE 
    , CELULAR_DDD INT 
	, CELULAR_NUMERO INT
    , RESIDENCIAL_DDD INT 
    , RESIDENCIAL_NUMERO INT 
    , CONTATO_DDD INT 
    , CONTATO_NUMERO INT
    , CONTATO_NOME VARCHAR(160)
    , PRIMARY KEY (IDALUNO)
);
