drop database if exists exercicio05;

create database exercicio05;

use exercicio05;

create table DEPARTAMENTO(
	IDDEPARTAMENTO INT NOT NULL,
    NOME_DEPARTAMENTO VARCHAR(45),
    RAMAL VARCHAR(45),
    NOME_RESPONSAVEL VARCHAR(160),
    PRIMARY KEY (IDDEPARTAMENTO)
);

CREATE TABLE COMPUTADOR(
	IDCOMPUTADOR INT NOT NULL,
    NUMERO_IDENTIFICACAO VARCHAR(45),
    FABRICANTE VARCHAR(45),
    MODELO VARCHAR(45),
    IDDEPARTAMENTO INT NOT NULL,
    primary key (IDCOMPUTADOR),
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (IDDEPARTAMENTO)
);

CREATE TABLE REDE(
	IDREDE INT NOT NULL,
    ENDERECO VARCHAR(45),
    MASCARA VARCHAR(45),
    IDCOMPUTADOR INT NOT NULL,
    PRIMARY KEY (IDREDE),
    foreign key (IDCOMPUTADOR) REFERENCES COMPUTADOR(IDCOMPUTADOR)
);