drop database if exists exercicio03;

create database exercicio03;

use exercicio03;

create table PEDIDO(
	IDPEDIDO INT NOT NULL,
    DATA_PEDIDO DATE,
    HORA TIME,
    CLIENTE varchar(100),
    primary KEY (IDPEDIDO)
);

CREATE TABLE PRODUTO(
	IDPRODUTO INT NOT NULL,
    NOME VARCHAR(100),
    PRECO VARCHAR(10),
    PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE PEDIDO_PRODUTO(
	IDPEDIDO INT NOT NULL,
    IDPRODUTO INT NOT NULL,
    PRIMARY KEY (IDPEDIDO, IDPRODUTO),
    FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO),
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);