drop database if exists exercicio04;

create database exercicio04;

use exercicio04;

create table USUARIO(
	IDUSUARIO INT NOT NULL,
    NOME VARCHAR(100),
    LOGIN VARCHAR(45),
    SENHA VARCHAR(45),
    DATA_CADASTRO DATE,
    PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE VIDEO(
	IDVIDEO INT NOT NULL,
    TITULO VARCHAR(45),
    CATEGORIA VARCHAR(45),
    DATA_PUBLICACAO DATE,
    primary key(IDVIDEO)
);

CREATE TABLE USUARIO_VIDEO(
	IDUSUARIO INT NOT NULL,
    IDVIDEO INT NOT NULL,
    PRIMARY KEY (IDUSUARIO, IDVIDEO),
    foreign key (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO),
    FOREIGN KEY (IDVIDEO) REFERENCES VIDEO(IDVIDEO)
);