DROP DATABASE IF EXISTS BDEXERCICIO04;

CREATE DATABASE DBEXERCICIO04;

USE DBEXERCICIO04;

CREATE TABLE LIVRO(
	IDLIVRO INT NOT NULL AUTO_INCREMENT
    , TITULO VARCHAR(100) NOT NULL
    , AUTOR VARCHAR(120) 
    , EDITORA VARCHAR(45)
    , ANO_DE_PUBLICACAO DATE 
    , PRIMARY KEY (IDLIVRO)
);