DROP DATABASE IF EXISTS  DBEXERCICIO03;

CREATE DATABASE DBEXERCICIO03;

USE DBEXERCICIO03;

CREATE TABLE CARRO(
	IDCARRO INT NOT NULL AUTO_INCREMENT
    , MARCA VARCHAR(45)
    , MODELO VARCHAR(45)
    , ANO_DE_FABRICACAO DATE 
    , ANO_DO_MODELO DATE 
    , PLACA CHAR(7) NOT NULL
    , COR VARCHAR(45)
    , NUMERO_DO_CHASSI VARCHAR(17)
    , PRIMARY KEY (IDCARRO)
);
    

