DROP DATABASE IF EXISTS atvhospede;

CREATE DATABASE atvhospede;

USE atvhospede;

CREATE TABLE HOSPEDE(
	IDHOSPEDE INT NOT NULL auto_increment
    , HOTEL_REDE VARCHAR(45)
    , HOTEL_MTUR varchar(45)
    , HOTEL_RAZAOSOCIAL VARCHAR(45)
    , HOTEL_CNPJ CHAR(14)
    , HOTEL_NOMEFANTASIA VARCHAR(45)
    , HOTEL_TIPO VARCHAR(45)
    , HOTEL_RUA VARCHAR(45)
    , HOTEL_NUMERO VARCHAR(45)
    , HOTEL_COMPLEMENTO VARCHAR(160)
    , HOTEL_BAIRRO VARCHAR(45)
    , HOTEL_CIDADE VARCHAR(45)
    , HOTEL_ESTADO CHAR(2)
    , HOTEL_CEP CHAR(8)
    , HOTEL_TELEFONE CHAR(13)
    , HOSPEDE_NOME VARCHAR(160)
    , HOSPEDE_TELEFONE CHAR(13)
    , HOSPEDE_PROFISSAO VARCHAR(45)
    , HOSPEDE_NACIONALIDADE VARCHAR(45)
    , HOSPEDE_NASCIMENTO DATE
    , HOSPEDE_SEXO CHAR(1)
    , HOSPEDE_DOCNUMERO CHAR(7)
    , HOSPEDE_DOCTIPO VARCHAR(45)
    , HOSPEDE_DOCORGAO VARCHAR(45)
    , HOSPEDE_CPF CHAR(11)
    , HOSPEDE_PROCCIDADE VARCHAR(45)
    , HOSPEDE_PROCESTADO VARCHAR(45)
    , HOSPEDE_PROCPAIS VARCHAR(45)
    , HOSPEDE_MOTIVO VARCHAR(45)
    , HOSPEDE_TRANSPORTE VARCHAR(45)
    , HOSPEDE_ACOMPANHANTE VARCHAR(45)
    , HOSPEDE_ENTRADA date
    , HOSPEDE_SAIDA DATE
    , HOSPEDE_UH varchar(45)
    , primary key (IDHOSPEDE)
);