-- APAGANDO O BANCO DE DADOS CASO EXISTA 
DROP DATABASE  IF EXISTS DBEXERCICIO07;

-- CRIANDO  A BASE DE DADOS
CREATE DATABASE DBEXERCICIO07;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO07;

-- CRIANDO AS TABELAS
CREATE TABLE PESSOA_PASSAPORTE (
	IDPESSOA INT NOT NULL
    , NOME VARCHAR(100)
    , IDPASSAPORTE INT NOT NULL
    , NUMERO VARCHAR(45)
    , PRIMARY KEY (IDPESSOA, IDPASSAPORTE)
    );