DROP  DATABASE IF EXISTS DBEXERCICIO08;

CREATE DATABASE DBEXERCICIO08;

USE DBEXERCICIO08;

CREATE TABLE ALUNO(
		IDALUNO INT NOT NULL
        , NOME VARCHAR(100)
		, PRIMARY KEY (IDALUNO)
);

CREATE TABLE PEDIDO(
	IDPEDIDO INT NOT NULL
    , PRODUTO VARCHAR(45)
    , IDALUNO INT NOT NULL
    , PRIMARY KEY (IDPEDIDO)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
);