DROP DATABASE IF EXISTS DBEXERCICIO09;

CREATE DATABASE DBEXERCICIO09;

USE DBEXERCICIO09;

CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL
    , NOME VARCHAR(100)
    , IDADE INT NOT NULL
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE PRODUTO(
	IDPRODUTO INT NOT NULL
    , NOME_PRODUTO VARCHAR(45)
    , PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE ALUNO_PRODUTO(
	IDALUNO INT NOT NULL
    , IDPRODUTO INT NOT NULL
    , PRIMARY KEY (IDALUNO, IDPRODUTO)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO(IDALUNO)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);